name: Overlays Modules CI
on: 
  workflow_call:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  unit-test:
    needs: [lint, validate]
    uses: ./.github/workflows/unit-test.yaml

  code-analysis:
    needs: [documentation]
    uses: ./.github/workflows/code-analysis.yaml